### PR TITLE
Switch to SSPL

### PR DESCRIPTION
**Pull request by cryi**
As discussed this switches to Breadcrumbs licensing to SSPL.

### CODE REVIEW

**Comment by nicolasochem** [comment]
I am offering a tezos baking service that includes payouts. If I understand this license correctly, under its terms I am allowed to use breadcrumbs for this service, as long as I open-source the entire software stack with which I am deploying the software. In my case, that's a helm chart. Is it accurate?

**Comment by cryi** [comment]
Yes, it is.

**Comment by nicolasochem** [comment]
then I'm fine contributing under this licence, thanks.

**Comment by cryi** [comment]
Hmm. I misread your comment @nicolasochem. Sorry for that. It is not accurate.

See:
```
  “Service Source Code” means the Corresponding Source for the Program or
  the modified version, and the Corresponding Source for all programs that
  you use to make the Program or modified version available as a service,
  including, without limitation, management software, user interfaces,
  application program interfaces, automation software, monitoring software,
  backup software, storage software and hosting software, all such that a
  user could run an instance of the service using the Service Source Code
  you make available.  
 ```

**Comment by kalouo** [comment]
Thanks @nicolasochem for your feedback. 

It seems breadcrumbs is at a juncture and I will make a decision in the coming days on how to move forward.

**Pull request merged**
